services:
  backend:
    build:
      context: ./backend
    container_name: audio-analysis-backend
    ports:
      - "8000:8000"
    networks:
      - app-network
    environment:
      - VARIABLE_NAME=value

  frontend:
    build:
      context: ./frontend
    container_name: audio-analysis-frontend
    ports:
      - "80:3000"
    networks:
      - app-network
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge